require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contributors", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Contributor. As you add validations to Contributor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Contributor.create! valid_attributes
      get users_contributors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contributor = Contributor.create! valid_attributes
      get users_contributor_url(contributor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_users_contributor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      contributor = Contributor.create! valid_attributes
      get edit_users_contributor_url(contributor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contributor" do
        expect {
          post users_contributors_url, params: { contributor: valid_attributes }
        }.to change(Contributor, :count).by(1)
      end

      it "redirects to the created contributor" do
        post users_contributors_url, params: { contributor: valid_attributes }
        expect(response).to redirect_to(users_contributor_url(Contributor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contributor" do
        expect {
          post users_contributors_url, params: { contributor: invalid_attributes }
        }.to change(Contributor, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post users_contributors_url, params: { contributor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contributor" do
        contributor = Contributor.create! valid_attributes
        patch users_contributor_url(contributor), params: { contributor: new_attributes }
        contributor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contributor" do
        contributor = Contributor.create! valid_attributes
        patch users_contributor_url(contributor), params: { contributor: new_attributes }
        contributor.reload
        expect(response).to redirect_to(contributor_url(contributor))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        contributor = Contributor.create! valid_attributes
        patch users_contributor_url(contributor), params: { contributor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contributor" do
      contributor = Contributor.create! valid_attributes
      expect {
        delete users_contributor_url(contributor)
      }.to change(Contributor, :count).by(-1)
    end

    it "redirects to the contributors list" do
      contributor = Contributor.create! valid_attributes
      delete users_contributor_url(contributor)
      expect(response).to redirect_to(users_contributors_url)
    end
  end
end
